/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Metamodel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Metamodel__factory>;
    getContractFactory(
      name: "Model",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Model__factory>;
    getContractFactory(
      name: "ModelInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ModelInterface__factory>;
    getContractFactory(
      name: "MyModelContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MyModelContract__factory>;
    getContractFactory(
      name: "MyStateMachine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MyStateMachine__factory>;

    getContractAt(
      name: "Metamodel",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Metamodel>;
    getContractAt(
      name: "Model",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Model>;
    getContractAt(
      name: "ModelInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ModelInterface>;
    getContractAt(
      name: "MyModelContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MyModelContract>;
    getContractAt(
      name: "MyStateMachine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MyStateMachine>;

    deployContract(
      name: "Metamodel",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Metamodel>;
    deployContract(
      name: "Model",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Model>;
    deployContract(
      name: "ModelInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ModelInterface>;
    deployContract(
      name: "MyModelContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MyModelContract>;
    deployContract(
      name: "MyStateMachine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MyStateMachine>;

    deployContract(
      name: "Metamodel",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Metamodel>;
    deployContract(
      name: "Model",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Model>;
    deployContract(
      name: "ModelInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ModelInterface>;
    deployContract(
      name: "MyModelContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MyModelContract>;
    deployContract(
      name: "MyStateMachine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MyStateMachine>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
