/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Model {
  export type PositionStruct = { x: BigNumberish; y: BigNumberish };

  export type PositionStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };

  export type PlaceStruct = {
    label: string;
    offset: BigNumberish;
    position: Model.PositionStruct;
    initial: BigNumberish;
    capacity: BigNumberish;
  };

  export type PlaceStructOutput = [
    label: string,
    offset: bigint,
    position: Model.PositionStructOutput,
    initial: bigint,
    capacity: bigint
  ] & {
    label: string;
    offset: bigint;
    position: Model.PositionStructOutput;
    initial: bigint;
    capacity: bigint;
  };

  export type TransitionStruct = {
    label: string;
    offset: BigNumberish;
    position: Model.PositionStruct;
    role: BigNumberish;
    delta: BigNumberish[];
    guard: BigNumberish[];
  };

  export type TransitionStructOutput = [
    label: string,
    offset: bigint,
    position: Model.PositionStructOutput,
    role: bigint,
    delta: bigint[],
    guard: bigint[]
  ] & {
    label: string;
    offset: bigint;
    position: Model.PositionStructOutput;
    role: bigint;
    delta: bigint[];
    guard: bigint[];
  };

  export type HeadStruct = {
    latestBlocks: BigNumberish[];
    sequence: BigNumberish;
    state: BigNumberish[];
    places: Model.PlaceStruct[];
    transitions: Model.TransitionStruct[];
  };

  export type HeadStructOutput = [
    latestBlocks: bigint[],
    sequence: bigint,
    state: bigint[],
    places: Model.PlaceStructOutput[],
    transitions: Model.TransitionStructOutput[]
  ] & {
    latestBlocks: bigint[];
    sequence: bigint;
    state: bigint[];
    places: Model.PlaceStructOutput[];
    transitions: Model.TransitionStructOutput[];
  };
}

export interface ModelInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "context" | "signal" | "signalMany"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "context", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "signal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signalMany",
    values: [BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "context", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signalMany", data: BytesLike): Result;
}

export interface ModelInterface extends BaseContract {
  connect(runner?: ContractRunner | null): ModelInterface;
  waitForDeployment(): Promise<this>;

  interface: ModelInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  context: TypedContractMethod<[], [Model.HeadStructOutput], "nonpayable">;

  signal: TypedContractMethod<
    [action: BigNumberish, scalar: BigNumberish],
    [void],
    "nonpayable"
  >;

  signalMany: TypedContractMethod<
    [actions: BigNumberish[], scalars: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "context"
  ): TypedContractMethod<[], [Model.HeadStructOutput], "nonpayable">;
  getFunction(
    nameOrSignature: "signal"
  ): TypedContractMethod<
    [action: BigNumberish, scalar: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signalMany"
  ): TypedContractMethod<
    [actions: BigNumberish[], scalars: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
