export const diningPhilosophers = {
        "modelType": "petriNet",
        "version": "v0",
        "places": {
            "chopstick0": { "offset": 0, "initial": 1, "x": 403, "y": 340 },
            "chopstick1": { "offset": 1, "initial": 1, "x": 534, "y": 345 },
            "chopstick2": { "offset": 2, "initial": 1, "x": 358, "y": 467 },
            "chopstick3": { "offset": 3, "initial": 1, "x": 547, "y": 461 },
            "chopstick4": { "offset": 4, "initial": 1, "x": 451, "y": 536 },
            "0right": { "offset": 5, "x": 415, "y": 181 },
            "0left": { "offset": 6, "x": 545, "y": 177 },
            "1right": { "offset": 7, "x": 719, "y": 288 },
            "1left": { "offset": 8, "x": 769, "y": 404 },
            "2left": { "offset": 9, "x": 686, "y": 584 },
            "2right": { "offset": 10, "x": 594, "y": 678 },
            "3left": { "offset": 11, "x": 315, "y": 679 },
            "3right": { "offset": 12, "x": 216, "y": 608 },
            "4right": { "offset": 13, "x": 148, "y": 397 },
            "4left": { "offset": 14, "x": 183, "y": 289 }
        },
        "transitions": {
            "0think": { "x": 478, "y": 106 },
            "0eat": { "x": 473, "y": 247 },
            "1eat": { "x": 654, "y": 396 },
            "2eat": { "x": 574, "y": 573 },
            "3eat": { "x": 333, "y": 556 },
            "4eat": { "x": 267, "y": 370 },
            "1think": { "x": 842, "y": 304 },
            "4think": { "x": 72, "y": 314 },
            "3think": { "x": 200, "y": 726 },
            "2think": { "x": 740, "y": 699 }
        },
        "arcs": [
            { "source": "chopstick0", "target": "0eat" },
            { "source": "chopstick1", "target": "0eat" },
            { "source": "chopstick0", "target": "4eat" },
            { "source": "chopstick2", "target": "4eat" },
            { "source": "chopstick1", "target": "1eat" },
            { "source": "chopstick3", "target": "1eat" },
            { "source": "chopstick2", "target": "3eat" },
            { "source": "chopstick4", "target": "3eat" },
            { "source": "chopstick4", "target": "2eat" },
            { "source": "chopstick3", "target": "2eat" },
            { "source": "0eat", "target": "0right" },
            { "source": "0eat", "target": "0left" },
            { "source": "1eat", "target": "1right" },
            { "source": "1eat", "target": "1left" },
            { "source": "2eat", "target": "2left" },
            { "source": "2eat", "target": "2right" },
            { "source": "3eat", "target": "3right" },
            { "source": "3eat", "target": "3left" },
            { "source": "4eat", "target": "4right" },
            { "source": "4eat", "target": "4left" },
            { "source": "0right", "target": "0think" },
            { "source": "0left", "target": "0think" },
            { "source": "1right", "target": "1think" },
            { "source": "1left", "target": "1think" },
            { "source": "2left", "target": "2think" },
            { "source": "2right", "target": "2think" },
            { "source": "4left", "target": "4think" },
            { "source": "4right", "target": "4think" },
            { "source": "3right", "target": "3think" },
            { "source": "3left", "target": "3think" },
            { "source": "4think", "target": "chopstick0" },
            { "source": "4think", "target": "chopstick2" },
            { "source": "0think", "target": "chopstick0" },
            { "source": "0think", "target": "chopstick1" },
            { "source": "1think", "target": "chopstick1" },
            { "source": "1think", "target": "chopstick3" },
            { "source": "2think", "target": "chopstick3" },
            { "source": "2think", "target": "chopstick4" },
            { "source": "3think", "target": "chopstick2" },
            { "source": "3think", "target": "chopstick4" }
        ]
    }

export const diningPhilosophersWithDeadlock = {
        "modelType": "petriNet",
        "version": "v0",
        "places": {
            "chopstick0": { "offset": 0, "initial": 1, "x": 403, "y": 340 },
            "chopstick1": { "offset": 1, "initial": 1, "x": 534, "y": 345 },
            "chopstick2": { "offset": 2, "initial": 1, "x": 358, "y": 467 },
            "chopstick3": { "offset": 3, "initial": 1, "x": 547, "y": 461 },
            "chopstick4": { "offset": 4, "initial": 1, "x": 451, "y": 537 },
            "0right": { "offset": 5, "x": 417, "y": 174 },
            "0left": { "offset": 6, "x": 545, "y": 177 },
            "1right": { "offset": 7, "x": 732, "y": 291 },
            "1left": { "offset": 8, "x": 765, "y": 379 },
            "2right": { "offset": 9, "x": 686, "y": 584 },
            "2left": { "offset": 10, "x": 590, "y": 675 },
            "3right": { "offset": 11, "x": 315, "y": 679 },
            "3left": { "offset": 12, "x": 216, "y": 608 },
            "4right": { "offset": 13, "x": 159, "y": 403 },
            "4left": { "offset": 14, "x": 196, "y": 296 }
        },
        "transitions": {
            "4takeLeft": { "x": 285, "y": 300 },
            "4takeRight": { "x": 243, "y": 430 },
            "4think": { "x": 84, "y": 313 },
            "0takeRight": { "x": 401, "y": 245 },
            "0takeLeft": { "x": 557, "y": 232 },
            "0think": { "x": 484, "y": 105 },
            "1takeRight": { "x": 643, "y": 294 },
            "1think": { "x": 814, "y": 309 },
            "1takeLeft": { "x": 674, "y": 434 },
            "2takeRight": { "x": 623, "y": 501 },
            "2think": { "x": 721, "y": 715 },
            "2takeLeft": { "x": 499, "y": 614 },
            "3takeRight": { "x": 395, "y": 625 },
            "3think": { "x": 200, "y": 726 },
            "3takeLeft": { "x": 281, "y": 525 }
        },
        "arcs": [
            { "source": "0right", "target": "0think" },
            { "source": "0left", "target": "0think" },
            { "source": "1right", "target": "1think" },
            { "source": "1left", "target": "1think" },
            { "source": "2right", "target": "2think" },
            { "source": "2left", "target": "2think" },
            { "source": "4left", "target": "4think" },
            { "source": "4right", "target": "4think" },
            { "source": "3left", "target": "3think" },
            { "source": "3right", "target": "3think" },
            { "source": "4think", "target": "chopstick0" },
            { "source": "4think", "target": "chopstick2" },
            { "source": "0think", "target": "chopstick0" },
            { "source": "0think", "target": "chopstick1" },
            { "source": "1think", "target": "chopstick1" },
            { "source": "1think", "target": "chopstick3" },
            { "source": "2think", "target": "chopstick3" },
            { "source": "2think", "target": "chopstick4" },
            { "source": "3think", "target": "chopstick2" },
            { "source": "3think", "target": "chopstick4" },
            { "source": "chopstick0", "target": "0takeRight" },
            { "source": "0takeRight", "target": "0right" },
            { "source": "chopstick1", "target": "0takeLeft" },
            { "source": "0takeLeft", "target": "0left" },
            { "source": "chopstick1", "target": "1takeRight" },
            { "source": "1takeRight", "target": "1right" },
            { "source": "chopstick3", "target": "1takeLeft" },
            { "source": "1takeLeft", "target": "1left" },
            { "source": "chopstick3", "target": "2takeRight" },
            { "source": "2takeRight", "target": "2right" },
            { "source": "chopstick4", "target": "2takeLeft" },
            { "source": "2takeLeft", "target": "2left" },
            { "source": "chopstick4", "target": "3takeRight" },
            { "source": "3takeRight", "target": "3right" },
            { "source": "chopstick2", "target": "3takeLeft" },
            { "source": "3takeLeft", "target": "3left" },
            { "source": "chopstick2", "target": "4takeRight" },
            { "source": "4takeRight", "target": "4right" },
            { "source": "chopstick0", "target": "4takeLeft" },
            { "source": "4takeLeft", "target": "4left" }
        ]
    }
