// public/petri-learn_test.ts — the JS side of the differentiable-fitting
// parity contract (run via `make test-js`, i.e. deno test).
//
// parity/learn/goldens.json is generated by go-pflow's learn package
// (`make learn-goldens`; parity/learn/gen/main.go) with solver
// JSParityOptions. This test replays every golden through
// public/petri-learn.js:
//
//   - point1Adjoint/point2Adjoint hold learn.MSELossAdjoint's reverse-mode
//     loss+grad at the same two points as point1/point2, asserted under the
//     SAME exact/tolerance rule as everything else. This checks JS-adjoint
//     against Go-adjoint, not adjoint against forward-mode sensitivities: the
//     adjoint forward pass is a plain (unaugmented) solve, so on an ADAPTIVE
//     case its accepted-step grid genuinely differs from the augmented
//     sensitivity ODE's grid (extra sensitivity states feed the same error
//     controller), and even a fixed-step case's gradient is a numerically
//     distinct computation from forward-mode's — bit-identical loss (same
//     dt grid) but NOT bit-identical grad. Both are correct; they are
//     different algorithms. See learn/adjoint.go's module doc.
//
//   - cases with exact=true (decay-fixed, tied-fixed: JSParityOptions with
//     adaptive=false) are asserted BIT-FOR-BIT: the JS arithmetic is
//     expression-for-expression identical to the Go code, no floating-point
//     sum in those nets has more than two independently ordered
//     contributions, and with the step controller off no transcendental is on
//     the path — so exact float64 equality is achieved and demanded for the
//     trajectory, sensitivities, losses, gradients, the full Adam iterate
//     sequence, the Nelder-Mead call sequence, and fit results. The
//     optimizers section (analytic Rosenbrock objective) is likewise
//     bit-exact, covering adam / gradient-descent / nelder-mead /
//     coordinate-descent (Adam's integer-exponent bias-correction pow is
//     ported bit-exactly as goPowInt).
//   - adaptive cases (decay, sir, tied: JSParityOptions as-is) are asserted
//     at 1e-9 relative instead, and that bound is genuinely unreachable to
//     tighten to zero: Go's adaptive step controller calls math.Pow, whose
//     fractional-exponent path runs SLEEF-derived amd64 assembly (even
//     CPU-dependent via FMA) that V8's Math.pow differs from by 1-2 ulp
//     (measured), perturbing an accepted dt in its last bit. sir additionally
//     sums three flux terms into place I from two transitions, and Go
//     iterates its maps in RANDOMIZED order, so even two Go generator runs
//     differ in the last bit there. sir's Adam sequence is excluded from the
//     goldens because a last-bit difference can flip an adaptive-step
//     acceptance and diverge macroscopically.
//
//     Measured agreement (2026-09-03, after the Tsit5 error-estimate fix that
//     took decay from 734 accepted steps to 13): trajectories and
//     sensitivities <= 2.2e-12, point losses/gradients <= 1.2e-11, and the
//     Adam iterate sequences <= 9.6e-11 (decay, call 21, grad[0]). Verified
//     mechanism, not guessed: on decay at that theta the Go and JS grids
//     agree bit-for-bit through step 4 and differ by exactly one ulp of t
//     from step 5 (the first controller step whose Math.pow rounds
//     differently), after which sensitivities differ by ~2e-15 relative —
//     Adam then compounds that through its moment estimates across 26
//     sequential evaluations. Before the fix the bound held at ~1e-14 only
//     because the O(dt) error estimate kept dt near 0.01, where one ulp of dt
//     is 1.7e-18 absolute; at dtmax=1 it is 2.2e-16, a hundredfold larger
//     perturbation of the same path. 1e-9 leaves 10x headroom over the
//     largest measured value.

import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import goldens from "../parity/learn/goldens.json" with { type: "json" };
import { fromJSON, setState, Tsit5 } from "./petri-solver.js";
import {
  LearnableProblem,
  ScalarRateFunc,
  SharedScalar,
  jsParityOptions,
  mseLoss,
  mseLossGrad,
  relativeMseLossGrad,
  minimizeGradient,
  minimize,
  fit,
  fitRates,
  newDataset,
  hingeRankLoss,
  mseLossAdjoint,
} from "./petri-learn.js";

const ADAPTIVE_REL_TOL = 1e-9;

// deno-lint-ignore no-explicit-any
type Any = any;

function expectNum(actual: number, expected: number, exact: boolean, ctx: string) {
  if (exact) {
    // === (not Object.is): 0 and -0 are the same value here.
    if (actual !== expected) {
      throw new Error(`${ctx}: expected exact ${expected}, got ${actual} (diff ${actual - expected})`);
    }
    return;
  }
  const scale = Math.max(Math.abs(actual), Math.abs(expected), 1);
  const err = Math.abs(actual - expected) / scale;
  if (!(err <= ADAPTIVE_REL_TOL)) {
    throw new Error(`${ctx}: expected ${expected} within ${ADAPTIVE_REL_TOL} rel, got ${actual} (rel err ${err})`);
  }
}

function expectVec(actual: number[], expected: number[], exact: boolean, ctx: string) {
  assertEquals(actual.length, expected.length, `${ctx}: length`);
  for (let i = 0; i < expected.length; i++) {
    expectNum(actual[i], expected[i], exact, `${ctx}[${i}]`);
  }
}

/** Build the rate-function map a case declares: independent scalars, plus one
 * SharedScalar instance per tied group. */
function buildRateFuncs(specs: Record<string, Any>) {
  const shared = new Map<string, SharedScalar>();
  const rfs: Record<string, Any> = {};
  for (const [name, spec] of Object.entries(specs) as [string, Any][]) {
    if (spec.kind === "scalar") {
      rfs[name] = new ScalarRateFunc(spec.rate);
    } else if (spec.kind === "shared") {
      if (!shared.has(spec.group)) shared.set(spec.group, new SharedScalar(spec.rate));
      rfs[name] = shared.get(spec.group);
    } else {
      throw new Error(`unknown rate kind ${spec.kind}`);
    }
  }
  return rfs;
}

function buildProblem(c: Any): LearnableProblem {
  const net = fromJSON(JSON.stringify(c.model));
  return new LearnableProblem(net, setState(net), c.tspan, buildRateFuncs(c.rateFuncs));
}

function caseDataset(c: Any) {
  return newDataset(c.dataset.times, c.dataset.observations, c.dataset.places);
}

/** Mirror of the generator's valueGrad: fitGradientCore's default gradient
 * evaluation (forward sensitivities + mseLossGrad, +Inf rejection). */
function makeValueGrad(prob: LearnableProblem, data: Any, indices: Any, solverOpts: Any) {
  return (theta: number[]): [number, number[] | null] => {
    prob.setAllParams(theta, indices);
    let sens;
    try {
      sens = prob.solveWithSensitivities(Tsit5(), solverOpts);
    } catch (_e) {
      return [Infinity, null];
    }
    if (sens.truncated) return [Infinity, null];
    const [loss, grad] = mseLossGrad(sens, data);
    if (!Number.isFinite(loss)) return [Infinity, null];
    for (const g of grad) if (!Number.isFinite(g)) return [Infinity, null];
    return [loss, grad];
  };
}

function caseSolverOpts(c: Any) {
  return { ...jsParityOptions(), adaptive: c.adaptive };
}

for (const c of (goldens as Any).cases) {
  const exact = c.exact as boolean;
  const mode = exact ? "exact float64" : `<= ${ADAPTIVE_REL_TOL} relative`;

  Deno.test(`learn parity [${c.name}]: sensitivities + losses (${mode})`, () => {
    const prob = buildProblem(c);
    const data = caseDataset(c);
    const [, indices] = prob.getAllParams();

    // Parameter packing: tied parameters count once, carriers alias one block.
    assertEquals(indices, c.paramIndex, "paramIndex");

    const sens = prob.solveWithSensitivities(Tsit5(), caseSolverOpts(c));
    assertEquals(sens.numParams, c.numParams, "numParams");
    assert(!sens.truncated, "truncated");

    // Step-for-step identical integration: same accepted step count and grid.
    assertEquals(sens.t.length - 1, c.steps, "steps");
    expectNum(sens.t[sens.t.length - 1], c.finalTime, exact, "finalTime");
    expectNum(sens.t[c.midIndex], c.midTime, exact, "midTime");

    for (const [place, want] of Object.entries(c.finalState) as [string, number][]) {
      expectNum(sens.sol.u[sens.t.length - 1][place], want, exact, `finalState[${place}]`);
    }
    for (const [place, row] of Object.entries(c.finalSens) as [string, number[]][]) {
      for (let p = 0; p < row.length; p++) {
        expectNum(sens.at(sens.t.length - 1, place, p)!, row[p], exact, `finalSens[${place}][${p}]`);
      }
    }
    for (const [place, row] of Object.entries(c.midSens) as [string, number[]][]) {
      for (let p = 0; p < row.length; p++) {
        expectNum(sens.at(c.midIndex, place, p)!, row[p], exact, `midSens[${place}][${p}]`);
      }
    }

    // Loss + gradient at the declared rates (point1)...
    const [ml, mg] = mseLossGrad(sens, data);
    expectNum(ml, c.point1.mse.loss, exact, "point1 mse loss");
    expectVec(mg, c.point1.mse.grad, exact, "point1 mse grad");
    const [rl, rg] = relativeMseLossGrad(sens, data);
    expectNum(rl, c.point1.relMse.loss, exact, "point1 relMse loss");
    expectVec(rg, c.point1.relMse.grad, exact, "point1 relMse grad");

    // ...and at a second fixed parameter point (point2).
    const prob2 = buildProblem(c);
    const [, idx2] = prob2.getAllParams();
    prob2.setAllParams(c.point2.params, idx2);
    const sens2 = prob2.solveWithSensitivities(Tsit5(), caseSolverOpts(c));
    const [ml2, mg2] = mseLossGrad(sens2, data);
    expectNum(ml2, c.point2.mse.loss, exact, "point2 mse loss");
    expectVec(mg2, c.point2.mse.grad, exact, "point2 mse grad");
    const [rl2, rg2] = relativeMseLossGrad(sens2, data);
    expectNum(rl2, c.point2.relMse.loss, exact, "point2 relMse loss");
    expectVec(rg2, c.point2.relMse.grad, exact, "point2 relMse grad");
  });

  Deno.test(`learn parity [${c.name}]: adjoint MSE loss+grad (${mode})`, () => {
    const data = caseDataset(c);

    // Point1: the declared rates.
    const prob = buildProblem(c);
    const adj1 = mseLossAdjoint(prob, data, Tsit5(), caseSolverOpts(c));
    assert(!adj1.truncated, "point1 adjoint truncated");
    expectNum(adj1.loss, c.point1Adjoint.loss, exact, "point1 adjoint loss");
    expectVec(adj1.grad, c.point1Adjoint.grad, exact, "point1 adjoint grad");

    // Point2: a second fixed parameter point.
    const prob2 = buildProblem(c);
    const [, idx2] = prob2.getAllParams();
    prob2.setAllParams(c.point2.params, idx2);
    const adj2 = mseLossAdjoint(prob2, data, Tsit5(), caseSolverOpts(c));
    assert(!adj2.truncated, "point2 adjoint truncated");
    expectNum(adj2.loss, c.point2Adjoint.loss, exact, "point2 adjoint loss");
    expectVec(adj2.grad, c.point2Adjoint.grad, exact, "point2 adjoint grad");
  });

  if (c.adam) {
    Deno.test(`learn parity [${c.name}]: Adam iterate sequence (${mode})`, () => {
      const prob = buildProblem(c);
      const data = caseDataset(c);
      const [params0, indices] = prob.getAllParams();
      const vg = makeValueGrad(prob, data, indices, caseSolverOpts(c));
      const calls: { theta: number[]; loss: number; grad: number[] | null }[] = [];
      const rec = (theta: number[]): [number, number[] | null] => {
        const [loss, grad] = vg(theta);
        calls.push({ theta: theta.slice(), loss, grad: grad ? grad.slice() : null });
        return [loss, grad];
      };
      const res = minimizeGradient(rec, params0, {
        method: "adam",
        maxIters: c.adam.maxIters,
        tolerance: 0,
      });

      assertEquals(calls.length, c.adam.calls.length, "fg call count");
      for (let i = 0; i < calls.length; i++) {
        expectVec(calls[i].theta, c.adam.calls[i].theta, exact, `adam call ${i} theta`);
        expectNum(calls[i].loss, c.adam.calls[i].loss, exact, `adam call ${i} loss`);
        expectVec(calls[i].grad!, c.adam.calls[i].grad, exact, `adam call ${i} grad`);
      }
      expectVec(res.params, c.adam.result.params, exact, "adam result params");
      expectNum(res.initialLoss, c.adam.result.initialLoss, exact, "adam initialLoss");
      expectNum(res.finalLoss, c.adam.result.finalLoss, exact, "adam finalLoss");
      assertEquals(res.iterations, c.adam.result.iterations, "adam iterations");
      assertEquals(res.converged, c.adam.result.converged, "adam converged");
      assertEquals(res.evals, c.adam.result.evals, "adam evals");
    });
  }

  if (c.nelder) {
    Deno.test(`learn parity [${c.name}]: Nelder-Mead call sequence (${mode})`, () => {
      const prob = buildProblem(c);
      const data = caseDataset(c);
      const [params0, indices] = prob.getAllParams();
      const calls: { theta: number[]; value: number }[] = [];
      const obj = (theta: number[]): number => {
        prob.setAllParams(theta, indices);
        const sol = prob.solve(Tsit5(), caseSolverOpts(c));
        const v = mseLoss(sol, data);
        calls.push({ theta: theta.slice(), value: v });
        return v;
      };
      const res = minimize(obj, params0, {
        method: "nelder-mead",
        maxIters: c.nelder.maxIters,
        tolerance: 0,
      });

      assertEquals(calls.length, c.nelder.calls.length, "f call count");
      for (let i = 0; i < calls.length; i++) {
        expectVec(calls[i].theta, c.nelder.calls[i].theta, exact, `nelder call ${i} theta`);
        expectNum(calls[i].value, c.nelder.calls[i].value, exact, `nelder call ${i} value`);
      }
      expectVec(res.params, c.nelder.result.params, exact, "nelder result params");
      expectNum(res.initialLoss, c.nelder.result.initialLoss, exact, "nelder initialLoss");
      expectNum(res.finalLoss, c.nelder.result.finalLoss, exact, "nelder finalLoss");
      assertEquals(res.iterations, c.nelder.result.iterations, "nelder iterations");
      assertEquals(res.converged, c.nelder.result.converged, "nelder converged");
    });
  }

  if (c.fit) {
    Deno.test(`learn parity [${c.name}]: fit (adam, MSE report) (${mode})`, () => {
      const prob = buildProblem(c);
      const data = caseDataset(c);
      const res = fit(prob, data, mseLoss, {
        method: "adam",
        maxIters: 10,
        tolerance: 0,
        solverMethod: Tsit5(),
        solverOptions: caseSolverOpts(c),
      });
      expectVec(res.params, c.fit.params, exact, "fit params");
      expectNum(res.initialLoss, c.fit.initialLoss, exact, "fit initialLoss");
      expectNum(res.finalLoss, c.fit.finalLoss, exact, "fit finalLoss");
      assertEquals(res.iterations, c.fit.iterations, "fit iterations");
      assertEquals(res.converged, c.fit.converged, "fit converged");
      assertEquals(res.evals, c.fit.evals, "fit evals");
    });
  }
}

// Analytic objective for optimizer parity: pure +,-,* in a fixed expression
// order, mirrored verbatim in parity/learn/gen/main.go.
function rosenbrock(x: number[]): [number, number[]] {
  const a = 1 - x[0];
  const b = x[1] - x[0] * x[0];
  const f = a * a + 100 * b * b;
  return [f, [-2 * a - 400 * x[0] * b, 200 * b]];
}

for (const run of (goldens as Any).optimizers) {
  Deno.test(`learn parity: ${run.method} over ${run.objective} (exact float64)`, () => {
    const calls: { theta: number[]; loss: number; grad: number[] | null }[] = [];
    let res: Any;
    if (run.method === "adam" || run.method === "gradient-descent") {
      const rec = (theta: number[]): [number, number[]] => {
        const [loss, grad] = rosenbrock(theta);
        calls.push({ theta: theta.slice(), loss, grad: grad.slice() });
        return [loss, grad];
      };
      res = minimizeGradient(rec, run.x0, {
        method: run.method,
        maxIters: run.maxIters,
        tolerance: 0,
      });
    } else {
      const rec = (theta: number[]): number => {
        const [loss] = rosenbrock(theta);
        calls.push({ theta: theta.slice(), loss, grad: null });
        return loss;
      };
      res = minimize(rec, run.x0, {
        method: run.method,
        maxIters: run.maxIters,
        tolerance: 0,
        stepSize: run.stepSize ?? 0.01,
      });
    }

    assertEquals(calls.length, run.calls.length, "call count");
    for (let i = 0; i < calls.length; i++) {
      expectVec(calls[i].theta, run.calls[i].theta, true, `${run.method} call ${i} theta`);
      expectNum(calls[i].loss, run.calls[i].loss, true, `${run.method} call ${i} loss`);
      if (run.calls[i].grad) {
        expectVec(calls[i].grad!, run.calls[i].grad, true, `${run.method} call ${i} grad`);
      }
    }
    expectVec(res.params, run.result.params, true, `${run.method} result params`);
    expectNum(res.initialLoss, run.result.initialLoss, true, `${run.method} initialLoss`);
    expectNum(res.finalLoss, run.result.finalLoss, true, `${run.method} finalLoss`);
    assertEquals(res.iterations, run.result.iterations, `${run.method} iterations`);
    assertEquals(res.converged, run.result.converged, `${run.method} converged`);
    if (run.method === "adam" || run.method === "gradient-descent") {
      assertEquals(res.evals, run.result.evals, `${run.method} evals`);
    }
  });
}

Deno.test("learn parity: hinge ranking loss (exact float64)", () => {
  for (const h of (goldens as Any).hinge) {
    const loss = hingeRankLoss(h.decisions, h.margin);
    expectNum(loss, h.loss, true, `hinge margin=${h.margin}`);
  }
});

// ---------------------------------------------------------------------------
// JS-only behavior (no Go golden): the convenience surface and the guards.
// ---------------------------------------------------------------------------

Deno.test("fitRates: recovers the decay rate from observations", () => {
  const c = (goldens as Any).cases.find((x: Any) => x.name === "decay");
  const net = fromJSON(JSON.stringify(c.model));
  const data = newDataset(c.dataset.times, c.dataset.observations, c.dataset.places);
  const res = fitRates(net, data, {
    rates: { decay: 0.1 },
    tspan: c.tspan,
    method: "adam",
    maxIters: 200,
    solverOptions: jsParityOptions(),
  });
  // Observations were synthesized near k = 0.5.
  assert(Math.abs(res.rates.decay - 0.5) < 0.05, `fitted decay ${res.rates.decay}`);
  assert(res.finalLoss < res.initialLoss, "loss decreased");
});

Deno.test("solveWithSensitivities: refuses a net place missing from the initial state", () => {
  const c = (goldens as Any).cases.find((x: Any) => x.name === "decay");
  const net = fromJSON(JSON.stringify(c.model));
  const prob = new LearnableProblem(net, { A: 10 }, [0, 1], { decay: new ScalarRateFunc(0.5) });
  let threw = false;
  try {
    prob.solveWithSensitivities(Tsit5(), jsParityOptions());
  } catch (e) {
    threw = true;
    assert(String(e).includes('missing from the initial state'), String(e));
  }
  assert(threw, "expected a missing-place refusal");
});

Deno.test("tied parameters: one theta, gradients summed across carriers", () => {
  const c = (goldens as Any).cases.find((x: Any) => x.name === "tied");
  const prob = buildProblem(c);
  const [params, indices] = prob.getAllParams();
  assertEquals(params.length, 1, "one packed parameter");
  assertEquals(indices.t1, indices.t2, "carriers alias one block");
  assertEquals(prob.numParams(), 1);

  // The shared-column gradient equals the sum of the two independent
  // per-transition gradients from an untied twin of the same net.
  const data = caseDataset(c);
  const sens = prob.solveWithSensitivities(Tsit5(), jsParityOptions());
  const [, gTied] = mseLossGrad(sens, data);

  const net2 = fromJSON(JSON.stringify(c.model));
  const untied = new LearnableProblem(net2, setState(net2), c.tspan, {
    t1: new ScalarRateFunc(0.25),
    t2: new ScalarRateFunc(0.25),
  });
  const sens2 = untied.solveWithSensitivities(Tsit5(), jsParityOptions());
  const data2 = caseDataset(c);
  const [, gUntied] = mseLossGrad(sens2, data2);
  assertEquals(gUntied.length, 2);
  // Same augmented system except for parameter packing; agreement is to
  // rounding (different accumulation shapes), not bit-exact.
  const sum = gUntied[0] + gUntied[1];
  assert(Math.abs(gTied[0] - sum) <= 1e-9 * Math.max(1, Math.abs(sum)),
    `tied grad ${gTied[0]} != sum of untied ${sum}`);
});
