/* Autogenerated file. Do not edit manually. */
import type {ContractDeployTransaction, ContractRunner, Signer} from "ethers";
/* tslint:disable */
/* eslint-disable */
import {Contract, ContractFactory, ContractTransactionResponse, Interface,} from "ethers";
import type {NonPayableOverrides} from "../common";
import type {Model, ModelInterface} from "../Model";

const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint8",
                name: "role",
                type: "uint8",
            },
            {
                indexed: true,
                internalType: "uint8",
                name: "actionId",
                type: "uint8",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "scalar",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "sequence",
                type: "uint256",
            },
        ],
        name: "SignaledEvent",
        type: "event",
    },
] as const;

const _bytecode =
    "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220794481a9542e9d293d274211c2ab199490db926bf2f49448226845a379ee1ee364736f6c63430008180033";

type ModelConstructorParams =
    | [signer?: Signer]
    | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
    xs: ModelConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Model__factory extends ContractFactory {
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;

    constructor(...args: ModelConstructorParams) {
        if (isSuperArgs(args)) {
            super(...args);
        } else {
            super(_abi, _bytecode, args[0]);
        }
    }

    static createInterface(): ModelInterface {
        return new Interface(_abi) as ModelInterface;
    }

    static connect(address: string, runner?: ContractRunner | null): Model {
        return new Contract(address, _abi, runner) as unknown as Model;
    }

    override getDeployTransaction(
        overrides?: NonPayableOverrides & { from?: string }
    ): Promise<ContractDeployTransaction> {
        return super.getDeployTransaction(overrides || {});
    }

    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
        return super.deploy(overrides || {}) as Promise<
            Model & {
            deploymentTransaction(): ContractTransactionResponse;
        }
        >;
    }

    override connect(runner: ContractRunner | null): Model__factory {
        return super.connect(runner) as Model__factory;
    }
}
